services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - device-gateway-network

  redis:
    image: redis:7-alpine
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - device-gateway-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - QDASH_API_URL=${QDASH_API_URL}
      - DEVICE_GATEWAY_PATH=${DEVICE_GATEWAY_PATH}
      - CONFIG_PATH=${CONFIG_PATH}
      - SCRIPTS_PATH=${SCRIPTS_PATH}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - C_FORCE_ROOT=${C_FORCE_ROOT}
    volumes:
      - ../device-gateway:/device-gateway
    depends_on:
      - postgres
      - redis
    networks:
      - device-gateway-network

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["uv", "run", "celery", "-A", "app.celery_app", "worker", "--loglevel=info"]
    env_file:
      - .env
    environment:
      - QDASH_API_URL=${QDASH_API_URL}
      - DEVICE_GATEWAY_PATH=${DEVICE_GATEWAY_PATH}
      - CONFIG_PATH=${CONFIG_PATH}
      - SCRIPTS_PATH=${SCRIPTS_PATH}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - C_FORCE_ROOT=${C_FORCE_ROOT}
    volumes:
      - ../device-gateway:/device-gateway
    depends_on:
      - postgres
      - redis
    networks:
      - device-gateway-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - device-gateway-network

volumes:
  postgres_data:
  redis_data:

networks:
  device-gateway-network:
    driver: bridge
